[package]
name = "tokio-uds"
version = "0.1.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tokio-uds"
homepage = "https://github.com/tokio-rs/tokio-uds"
documentation = "https://tokio-rs.github.io/tokio-uds"
description = """
Unix Domain sockets for Tokio
"""

[dependencies]
mio = "0.6"
mio-uds = "0.6.1"
futures = "0.1"
tokio-core = { git = "https://github.com/tokio-rs/tokio-core"}
log = "0.3"
